### ISSUE TITLE
Error occured in stage GenerateProbModel

### ISSUE THREAD

**Issue by shawnzhangyx** [dhkron/PSYCHIC#1]
Hi, 

I saw your manuscript on BioArxiv and was very interested in using your software. However, as I was running the example data you provided, I got the following error: 
> 
> Creating a Dixon-compatible matrix...
> Done!
> Running stage DixonDI
> Stage DixonDI done in 0.884799 seconds
> Running stage DixonDomainHMMCalling
> Stage DixonDomainHMMCalling done in 673.728319 seconds
> Running stage DixonDomains1
> Stage DixonDomains1 done in 0.092609 seconds
> Running stage DixonDomains2
> Stage DixonDomains2 done in 0.056782 seconds
> Running stage FixDomainFormat
> Stage FixDomainFormat done in 0.007951 seconds
> Running stage FixMatrixFormat
> Stage FixMatrixFormat done in 0.297036 seconds
> Skipping stage domain_debug
> Running stage GenerateProbModel
> Stage GenerateProbModel done in 13.879662 seconds
> Error occured in stage GenerateProbModel

Could you help me figure out where the problem is? Thank you!

Best,
Shawn

**Comment by dhkron** [comment]
Hello,

Thanks for the feedback!
As for the problem - when GenerateProbModel fails it writes an error log to
a file named "*.mdump2", could you post some of it?
Also, two possible ("known") causes -
1) If the original input matrix is not symmetric, it usually causes some
problems down the road. [That is a constraint of an external library]
2) There was an issue with last line of  '*.domains.txt' (right after stage
"DixonDomains2"), that was fixed in the last commit last knight.

Gil

**Comment by shawnzhangyx** [comment]
Hi Gil, 

Thanks for your prompt response! Here is the output in the .mdump2 file: 

> 
> Creating diag matrix... Done! 0.0888 seconds^M
> Extracting TAD/Bg matrix-masks... Done! 5.5086 seconds^M
> Gaussianing... AAABBBCCCAAA
> ans =
> 
> Undefined function or variable "GMModel".
> 
> Error in AnalyzeGMM (line 19)
>         a_gmm{i}=GMModel;
> 
> Error in GenerateModelFromTADs (line 46)
> a_gmm_tad = AnalyzeGMM(a_tad,MIN_DIAG,MAX_DIAG,1);
> 

I'll run it again.

**Comment by dhkron** [comment]
I've found a potential error in AnalyzeGMM.m file, there was an issue with
the try-catch block. Should not throw this error now.

**Comment by shawnzhangyx** [comment]
Hi Gil, 

The previous bug was fixed, but I ran into another problem:

> Stage DebugHierarchies done in 9.144668 seconds
> Error occured in stage DebugHierarchies

Here is the log in the .dump7 file: 

> [^HWarning: Struct field assignment overwrites a value with class "double". See MATLAB R14SP2
> Release Notes, Assigning Nonstructure Variables As Structures Displays Warning, for
> details.]^H
> [^H> In SaveFigure at 2
>   In PlotHrrcBed at 72]^H
> AAABBBCCCAAA
> ans =
> 
> Reference to non-existent field 'Position'.
> 
> Error in SaveFigure (line 4)
>     handle.PaperPosition = handle.Position;
> 
> Error in PlotHrrcBed (line 72)
>         SaveFigure(g,figPath)
>

**Comment by dhkron** [comment]
Hello Shawn,

I am not sure why this one happens (could not reproduce), but i've pushed a
possible fix. Perhaps '*gcf*' function in *PlotHrrcBed.m* does not pass the
figure handle properly on some setups.

**Comment by shawnzhangyx** [comment]
Hi Gil, 
Thanks for your time! I'm still having the same issue after updating to your latest commit. Maybe this is system-related. One more question: Is the example you provided working fine on your own machine when you install this software from scratch (clone from Github)?

**Comment by dhkron** [comment]
Hello Shawn,

Sorry for the delay. I took your advice and cloned the code into a clean
MacOS, and was able to reproduce the error :)
It was a miss-configured matlab cli arguments inside the image saving
routine.
The example now runs smoothly from a cloned code

Gil

**Comment by shawnzhangyx** [comment]
Hi Gil, 

It is working. Thank you! Closing the ticket.
